import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Sparkles, Library, BookOpen, GraduationCap, Bot } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link className="flex items-center justify-center gap-2" href="/">
          <Sparkles className="h-6 w-6 text-primary" />
          <span className="text-xl font-bold">StudyBomBibi</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="/login">
            Login
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="/register">
            Register
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex justify-center">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
                  Study Smarter, Not Harder
                </h1>
                <p className="mx-auto max-w-175 text-muted-foreground md:text-xl">
                  The all-in-one AI study companion. Generate study plans, quizzes, and chat with your materials.
                </p>
              </div>
              <div className="space-x-4">
                <Link href="/dashboard">
                  <Button className="h-11 px-8">Get Started</Button>
                </Link>
                <Link href="/register">
                  <Button variant="outline" className="h-11 px-8">Sign Up</Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted/50 flex justify-center">
          <div className="container px-4 md:px-6"> 
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              <Card>
                <CardHeader>
                  <BookOpen className="h-10 w-10 mb-2 text-primary" />
                  <CardTitle>AI Study Planner</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>
                    Customized study plans generated by AI based on your schedule and preferred learning style.
                  </CardDescription>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Library className="h-10 w-10 mb-2 text-primary" />
                  <CardTitle>Centralized Library</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>
                    Upload and organize all your lecture notes and slides. Supported formats: PDF, Images, Text.
                  </CardDescription>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <Bot className="h-10 w-10 mb-2 text-primary" />
                  <CardTitle>AI Assistant</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>
                    Chat with your notes. Get instant answers and explanations for complex topics.
                  </CardDescription>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <GraduationCap className="h-10 w-10 mb-2 text-primary" />
                  <CardTitle>Exam Prep</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>
                    Generate quizzes and past year paper style questions to test your knowledge.
                  </CardDescription>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">© 2026 StudyBomBibi. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}
